### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by cukabeka** [yakamara/redaxo_ycom#122]
Nach einem misslungenen Update von ycom 1 auf 2 und nun einem kompletten re-install (inkl DROP rex_ycom_user vorher) bekomme ich beim install den hier:

    AddOn ycom konnte aus folgendem Grund nicht installiert werden:
    SQL error: Error while executing statement "ALTER TABLE `rex_ycom_user` ADD `activation_key` varchar(255) NOT NULL"! SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'activation_key'

**Comment by skerbis** [comment]
@cukabeka den Fehler habe ich auch. Ich habe jetzt Schritt für Schritt jedesmal das doppelte Feld in yform Tablemanager entfernt .. danach war gut.

**Comment by dergel** [comment]
war das jeweils nach einem update ? bei einer neuinstallation ging alles ? yform aktuell gewesen ? danke für infos.

**Comment by skerbis** [comment]
Beim re-installieren tritt der Fehler auf.

**Comment by dergel** [comment]
aktuellste yform ?

**Comment by skerbis** [comment]
in 2.0 ... Githubversion nicht getestet

**Comment by dergel** [comment]
könntest du die githubversion testen..

**Comment by dergel** [comment]
es gibt aber schon 2.2 .. damit auch ?

**Comment by skerbis** [comment]
ycom 2.2? Ist doch nicht released

**Comment by dergel** [comment]
und github version ycom .. und wenn das auch nicht geht.. github yform ?

**Comment by dergel** [comment]
hast du nochmal zeit zu testen mit der aktuellen 2.1b ?

**Comment by skerbis** [comment]
****Getestet mit yform** 2.3b und com 2.1b**

Getestet:
Neuinstallation - ok 
Update 2.0 > 2.1b - ok 
Reinstall: ok 

**Update von 1.0 > 2.1b** 

> AddOn ycom konnte aus folgendem Grund nicht installiert werden:
> SQL error: Error while executing statement "ALTER TABLE `rex_ycom_user` ADD `activation_key` varchar(255) NOT NULL"! SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'activation_key'

**Comment by cukabeka** [comment]
ich konnte das problem nach etlichen versuchen übrigens in den griff bekommen, indem ich die userrechte für die seite angepasst habe. also ganz einfach auf der rechten seite alle gruppen entfernt und zugriff für alle ermöglicht..
![image](https://user-images.githubusercontent.com/688274/27744234-035845ea-5dbf-11e7-9d40-1bfca0cbf70c.png)

**Comment by olien** [comment]
Den Fehler kann ich bestätigen..

ycom deinstalliert, gelöscht und neuinstalliert...

**Comment by DavidBruchmann** [comment]
Hab noch einen bei frischer Installation:
Error while executing statement "SELECT FOUND_ROWS() as rows"! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows' at line 1

Leider ein Blocker für dringende Arbeit ....

**Comment by DavidBruchmann** [comment]
Error while executing statement "SELECT FOUND_ROWS() as rows"! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows' at line 1
#0 ... \redaxo\redaxo\src\core\lib\list.php(149): rex_sql->setQuery('SELECT FOUND_RO...')
#1 ... \redaxo\redaxo\src\core\lib\list.php(176): rex_list->__construct('select `id`,`na...', '200', NULL, false)
#2 ... \redaxo\redaxo\src\addons\yform\plugins\manager\lib\yform\manager.php(510): rex_list::factory('select `id`,`na...', '200')
#3 ... \redaxo\redaxo\src\addons\yform\plugins\manager\pages\data_edit.php(21): rex_yform_manager->getDataPage()
#4 ... \redaxo\redaxo\src\addons\yform\pages\index.php(3): include('...')
#5 ... \redaxo\redaxo\src\core\lib\packages\package.php(228): include('...')
#6 ... \redaxo\redaxo\src\core\lib\be\controller.php(456): rex_package->includeFile('pages\\index.php', Array)
#7 ... \redaxo\redaxo\src\core\lib\be\controller.php(403): rex_be_controller::includePath('...')
#8 ... \redaxo\redaxo\src\core\backend.php(138): rex_be_controller::includeCurrentPage()
#9 ... \redaxo\redaxo\src\core\boot.php(107): require('...')
#10 ... \redaxo\redaxo\index.php(9): require('...')
#11 {main}

**Comment by staabm** [comment]
liegt vermutlich an der mariadb version, welche version verwendest du?

**Comment by DavidBruchmann** [comment]
die neuste, aber daran liegts nicht.
ich habe momentan 5.3.0 laufen und habe in 5.4 gesehen, daß die Zeile schon gefixt ist in lib/list.php
`        $sql->setQuery('SELECT FOUND_ROWS() as '. $sql->escapeIdentifier('rows'));`
Also diesbezüglich Entwarnung.

**Comment by staabm** [comment]
ach stimmt.. das hab sogar ich gefixed.. gab noch kein release seitdem ;)

**Comment by DavidBruchmann** [comment]
Also der Fehler ist ein Blocker:
`AddOn ycom konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement "ALTER TABLE `rex_ycom_user` ADD `activation_key` varchar(255) NOT NULL"! SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'activation_key'`  
Löschen und Neuinstallieren klappt nicht.
Aktuelle Versionen: Redaxo-5.3.0, yform-2.3b2, ycom-2.1b2

**Comment by DavidBruchmann** [comment]
Hab noch einige Fehler in der Logdatei gefunden, muss aber Suchen weshalb Zugriff dort verboten ist, kanns mir momentan nicht erklären, besonders bei boot.php

`[Mon Sep 11 19:33:08.791498 2017] [access_compat:error] [pid 1516:tid 1708] [client 127.0.0.1:53408] AH01797: client denied by server configuration: /redaxo-5.3.0/redaxo/data/.redaxo, referer: http://redaxo-5.3.loc/redaxo/index.php?page=setup&step=3&lang=de_de
[Mon Sep 11 19:33:08.805499 2017] [access_compat:error] [pid 1516:tid 1708] [client 127.0.0.1:53408] AH01797: client denied by server configuration: /redaxo-5.3.0/redaxo/cache/.redaxo, referer: http://redaxo-5.3.loc/redaxo/index.php?page=setup&step=3&lang=de_de
[Mon Sep 11 19:33:08.819499 2017] [access_compat:error] [pid 1516:tid 1696] [client 127.0.0.1:53416] AH01797: client denied by server configuration: /redaxo-5.3.0/redaxo/src/core/boot.php, referer: http://redaxo-5.3.loc/redaxo/index.php?page=setup&step=3&lang=de_de
[Mon Sep 11 19:36:40.562610 2017] [access_compat:error] [pid 1516:tid 1736] [client 127.0.0.1:53485] AH01797: client denied by server configuration: /redaxo-5.3.0/redaxo/data/.redaxo, referer: http://redaxo-5.3.loc/redaxo/index.php?page=setup&step=3&lang=de_de
[Mon Sep 11 19:36:40.592612 2017] [access_compat:error] [pid 1516:tid 1696] [client 127.0.0.1:53496] AH01797: client denied by server configuration: /redaxo-5.3.0/redaxo/src/core/boot.php, referer: http://redaxo-5.3.loc/redaxo/index.php?page=setup&step=3&lang=de_de
[Mon Sep 11 19:36:40.609613 2017] [access_compat:error] [pid 1516:tid 1708] [client 127.0.0.1:53497] AH01797: client denied by server configuration: /redaxo-5.3.0/redaxo/cache/.redaxo, referer: http://redaxo-5.3.loc/redaxo/index.php?page=setup&step=3&lang=de_de`

**Comment by DavidBruchmann** [comment]
Liegt an der .htaccess, Frage ist warum soll dort ein Zugriff stattfinden?

**Comment by DavidBruchmann** [comment]
Andere Frage: wie kann man ein Addon manuell aktivieren?

**Comment by DavidBruchmann** [comment]
Hab die folgende Zeile in table_api.php vorübergehend auskommentiert, damit klappts. Ist mir übrigens schleierhaft, weshalb dort noch `ADD` steht, da die Feldauswahl bereits auf bestehenden Feldern zu bestehen scheint:
`// $c->setQuery('ALTER TABLE `' . $table['table_name'] . '` ADD `' . $type_label . '` ' . $dbtype . $null);`

**Comment by dergel** [comment]
ich kann es leider immernoch nicht nachvollziehen. deswegen erstmal nach hinten verschoben.

**Comment by dergel** [comment]
liegt wohl eher an yform und dem .json import. Könnt Ihr das mit der aktuellen YForm und der github Version gegenprüfen ?

**Comment by DavidBruchmann** [comment]
Installation funktioniert in der heutigen Version 11,10,2017.

**Comment by erraiva** [comment]
Hallo zusammen, mein Eindruck ist, dass die Aktivierung von ycom nur bei einer kompletten Neuinstallation richtig klappt. Also leere DB, keine rex_user table. Dann dieses Addon zuerst aktivieren, phpmailer und yform natürlich. Ob die Reihenfolge wichtig ist weiß ich nicht ;-)
Bei dem Import der demo_community gehts dann aber weiter mit einer Fehlermeldung: 
`Error while executing statement "SELECT SQL_CALC_FOUND_ROWS id, prio, name, table_name, status, hidden, import, export, search, mass_deletion, mass_edit, history from `rex_yform_table` order by prio,table_name LIMIT 0,30"! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mass_edit' in 'field list'. `
Ich habe rex_yform_table dann von einer anderen Installation genommen, wo mass_edit vorhanden war.
Weiter gehts mit dem Login. Ob eigens angelegter User oder hans@trapper:
`Error while executing statement "SELECT `rex_ycom_user`.* FROM `rex_ycom_user` WHERE `` = :p1 ORDER BY `login` DESC" using params {"p1":"hans@trapper.de"}! SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause'`.
Wenn ich das recht lese wird das Select-Statement falsch generiert.

Hoffe das hilft weiter.
VG Heinz
